name: example - static
on:
  push:
  #  branches:
  #    - master

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        id: now-deployment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-org-id: ${{ secrets.NOW_ORG_ID }}
          now-project-id: $$ {{ secrets.NOW_PROJECT_ID_STATIC }}
          now-args: '--prod'
          working-directory: example/static

